# Reference: 
#  https://py-pkgs.org/03-how-to-package-a-python#building-documentation
#  https://github.com/peaceiris/actions-gh-pages
name: GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
